import { useEffect, useState } from 'react';
import { dateText } from './api';
import { useData, Loading, Empty, Feedback, Field } from './ui';
interface AuditResult { items: { id: string; actor_id: string | null; action: string; target_id: string | null; details: unknown; created_at: string }[]; total: number; page: number; page_size: number; pages: number }
export function AuditPanel({ userId }: { userId: string }) {
  const key = `audit-page:${userId}`;
  const [choice, setChoice] = useState(() => { try { const saved = JSON.parse(sessionStorage.getItem(key) || '{}'); return { page: Number.isSafeInteger(saved.page) && saved.page > 0 && saved.page <= 2147483647 ? saved.page : 1, size: saved.size === 100 ? 100 : 50 }; } catch { return { page: 1, size: 50 }; } });
  const [jump, setJump] = useState('');
  const list = useData<AuditResult>(`/audit/page?page=${choice.page}&page_size=${choice.size}`);
  useEffect(() => { try { sessionStorage.setItem(key, JSON.stringify(choice)); } catch { /* Storage may be disabled. */ } }, [key, choice]);
  useEffect(() => { if (list.data) setChoice(c => c.page === list.data!.page ? c : ({ ...c, page: list.data!.page })); }, [list.data]);
  const data = list.data;
  return <><div className="page-intro"><div><h2>审计日志</h2><p>查看当前权限范围内的操作记录与监管访问。</p></div><button className="secondary" onClick={list.reload} disabled={list.loading}>刷新</button></div><Feedback error={list.error}/>{list.error && <button className="secondary" onClick={list.reload}>重试</button>}<div className="pagination"><Field label="每页条数"><select value={choice.size} onChange={e => { setChoice({ page: 1, size: Number(e.target.value) }); setJump(''); }}><option value={50}>50</option><option value={100}>100</option></select></Field><span role="status">{data ? `共 ${data.total} 条 · 第 ${data.page} / ${data.pages} 页` : list.loading ? '正在加载页数…' : '暂无法读取页数'}</span><button className="secondary" disabled={list.loading || !data || data.page <= 1} onClick={() => setChoice(c => ({ ...c, page: c.page - 1 }))}>上一页</button><button className="secondary" disabled={list.loading || !data || data.page >= data.pages} onClick={() => setChoice(c => ({ ...c, page: c.page + 1 }))}>下一页</button><form onSubmit={e => { e.preventDefault(); if (!data || list.loading) return; const page = Number(jump); if (Number.isInteger(page) && page >= 1 && page <= data.pages) { setChoice(c => ({ ...c, page })); setJump(''); } }}><label>跳至 <input aria-label="跳转页码" type="number" min={1} max={data?.pages ?? 1} step={1} required value={jump} onChange={e => setJump(e.target.value)} disabled={list.loading || !data}/></label><button className="secondary" disabled={list.loading || !data}>跳转</button></form></div>{list.loading ? <Loading/> : data && (data.items.length ? <div className="table-wrap"><table><thead><tr>{['时间', '操作', '操作人 ID', '目标 ID', '详情', '记录 ID'].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{data.items.map(row => <tr key={row.id}><td>{dateText(row.created_at)}</td><td>{row.action}</td><td>{row.actor_id ?? '—'}</td><td>{row.target_id ?? '—'}</td><td><pre>{JSON.stringify(row.details, null, 2)}</pre></td><td>{row.id}</td></tr>)}</tbody></table></div> : <Empty text="暂无审计记录" description="当前权限范围内没有操作记录。"/>)}</>;
}
