import { useState } from 'react';
import { api, post, errorText } from './api';
import { useData, Loading, Feedback, Modal, Form, Field, value } from './ui';
interface Entry { id: string; name: string; org_id?: string; legacy: boolean; can_edit: boolean; can_delete: boolean }
interface Catalog { organizations: Entry[]; departments: Entry[]; can_create_org: boolean; can_create_department: boolean }
export function DirectoryPanel() {
  const list = useData<Catalog>('/directory/management');
  const [editing, setEditing] = useState<{kind: string; row?: Entry} | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  async function remove(kind: string, row: Entry) {
    if (!window.confirm(`确认删除“${row.name}”？有用户、部门、群组或资源引用时无法删除；不会级联删除，历史 ID 不可复用。`)) return;
    setBusy(true); setError('');
    try { await api(`/directory/${kind}/${encodeURIComponent(row.id)}`, {method:'DELETE'}); list.reload(); setSuccess('目录已删除。'); }
    catch(e) { setError(errorText(e)); } finally { setBusy(false); }
  }
  return <><div className="page-intro"><div><h2>组织与部门</h2><p>管理中文名称与目录；编辑不会改变 ID 或所属组织。</p></div><button className="secondary" disabled={list.loading || busy} onClick={list.reload}>刷新</button></div><Feedback error={error || list.error} success={success}/>{list.loading ? <Loading/> : list.data && (['organizations','departments'] as const).map(kind=><section className="panel" key={kind}><div className="section-heading"><h2>{kind==='organizations'?'组织':'部门'}</h2>{(kind==='organizations'?list.data!.can_create_org:list.data!.can_create_department) && <button className="primary" disabled={busy} onClick={()=>setEditing({kind})}>新增{kind==='organizations'?'组织':'部门'}</button>}</div><div className="table-wrap"><table><thead><tr><th>名称 / ID</th>{kind==='departments' && <th>所属组织</th>}<th>操作</th></tr></thead><tbody>{list.data![kind].map(row=><tr key={`${row.org_id || ''}/${row.id}`}><td><strong>{row.name}</strong><small>{row.id}{row.legacy?'（历史 ID）':''}</small></td>{kind==='departments' && <td>{list.data!.organizations.find(o=>o.id===row.org_id)?.name || row.org_id}</td>}<td><div className="actions">{row.can_edit && <button className="secondary" disabled={busy} onClick={()=>setEditing({kind,row})}>编辑</button>}{row.can_delete && <button className="danger-button" disabled={busy} onClick={()=>void remove(kind,row)}>{busy?'处理中…':'删除'}</button>}{!row.can_edit && !row.can_delete && '只读'}</div></td></tr>)}</tbody></table></div></section>)}{editing && <Modal title={`${editing.row?'编辑':'新增'}${editing.kind==='organizations'?'组织':'部门'}`} close={()=>{if(!busy)setEditing(null);}}><Form label="保存" submit={async f=>{setBusy(true);try {const body={name:value(f,'name'),...(!editing.row && editing.kind==='departments'?{org_id:value(f,'org_id')}:{})};return await (editing.row?api(`/directory/${editing.kind}/${encodeURIComponent(editing.row.id)}`,{method:'PATCH',body:JSON.stringify(body)}):post(`/directory/${editing.kind}`,body));}finally{setBusy(false);}}} onSuccess={()=>{setEditing(null);list.reload();setSuccess('已保存。');}}><Field label="名称"><input name="name" required maxLength={200} defaultValue={editing.row?.name}/></Field>{editing.row ? <p>ID：{editing.row.id}；所属组织保持不变。</p> : editing.kind==='departments' && <Field label="所属组织"><select name="org_id" required defaultValue=""><option value="">请选择组织</option>{list.data?.organizations.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></Field>}<button type="button" className="secondary" onClick={()=>setEditing(null)}>取消</button></Form></Modal>}</>;
}
