import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bot, LayoutDashboard, MessagesSquare, Users, UsersRound, Layers, KeyRound, Cable, ScrollText, LogOut, Menu, ArrowRight, ShieldCheck, ChevronRight, LoaderCircle } from 'lucide-react';
import { Toaster } from 'sonner';
import { api, post, roles, errorText, ApiError } from './api';
import type { User } from './api';
import { Form, Field, Feedback, Loading, value } from './ui';
import { Overview, Management, pageNames } from './Management';
import type { Page } from './Management';
import { Chat } from './Chat';
import './style.css';
import { useRoute, canAccessPage } from './route';
const navigation = [{ page: 'overview', icon: LayoutDashboard }, { page: 'chat', icon: MessagesSquare }, { page: 'connections', icon: Cable }, { page: 'directory', icon: Layers }, { page: 'users', icon: Users }, { page: 'groups', icon: UsersRound }, { page: 'resources', icon: Layers }, { page: 'bindings', icon: KeyRound }, { page: 'integrations', icon: Cable }, { page: 'audit', icon: ScrollText }] as const;
export function App() {
  const { route, navigate: changeRoute } = useRoute();
  const page = route.page;
  const [user, setUser] = useState<User | null>(null); const [checking, setChecking] = useState(true); const [authError, setAuthError] = useState(''); const [mobileMenu, setMobileMenu] = useState(false); const [logoutBusy, setLogoutBusy] = useState(false); const [logoutError, setLogoutError] = useState('');
  const [initialized, setInitialized] = useState<boolean | null>(null);
  const [setupComplete, setSetupComplete] = useState(false);
  async function check() { setChecking(true); setAuthError(''); setInitialized(null); try { const state = await api<boolean>('/setup/status'); if (typeof state !== 'boolean') throw new Error('初始化状态响应无效'); setInitialized(state); if (state) setUser(await api<User>('/auth/me')); } catch (e) { if (!(e instanceof ApiError && e.status === 401)) setAuthError(errorText(e)); } finally { setChecking(false); } }
  useEffect(() => { void check(); const expire = () => { setUser(null); setAuthError('登录已过期，请重新登录。'); }; window.addEventListener('hub-session-expired', expire); return () => window.removeEventListener('hub-session-expired', expire); }, []);
  async function logout() { setLogoutBusy(true); setLogoutError(''); try { await post('/auth/logout', {}); setUser(null); changeRoute({ page: 'overview', conversationId: null }, true); } catch (e) { setLogoutError(errorText(e)); } finally { setLogoutBusy(false); } }
  function navigate(next: Page) { if (user && canAccessPage(user, next)) changeRoute({ page: next, conversationId: null }); setMobileMenu(false); }
  useEffect(() => { if (user && !canAccessPage(user, route.page)) changeRoute({ page: 'overview', conversationId: null }, true); }, [user, route.page]);
  if (checking) return <div className="boot"><Bot size={38}/><Loading/></div>;
  if (!user && initialized !== true) return <div className="login-page"><section className="login-form"><div className="login-form-inner"><h2>{initialized === false ? '初始化管理员' : '连接工作空间'}</h2><Feedback error={authError}/>{initialized === null ? <button onClick={() => void check()}>重新检查服务连接</button> : <><p>创建首个账号，成为工作空间超级管理员。完成后使用该账号登录。</p><Form label="创建管理员" submit={async f => { const password = String(f.get('password')); if (password !== String(f.get('confirmPassword'))) throw new Error('两次输入的密码不一致'); try { await post('/setup/bootstrap', { name: value(f, 'name'), email: value(f, 'email'), password }); setInitialized(true); setSetupComplete(true); setAuthError(''); } catch (e) { if (e instanceof ApiError && e.status === 409) { setInitialized(true); setAuthError('初始化已完成，请使用管理员账号登录。'); } else throw e; } }} onSuccess={() => {}}><Field label="姓名"><input name="name" required maxLength={200} autoComplete="name"/></Field><Field label="邮箱"><input name="email" type="email" required maxLength={320} autoComplete="username"/></Field><Field label="密码（至少 12 位）"><input name="password" type="password" required minLength={12} maxLength={1024} autoComplete="new-password"/></Field><Field label="确认密码"><input name="confirmPassword" type="password" required minLength={12} maxLength={1024} autoComplete="new-password"/></Field></Form></>}</div></section></div>;
  if (!user) return <div className="login-page"><section className="login-story"><div className="brand"><span><Bot size={26}/></span><div>Agent Hub<small>企业智能协作平台</small></div></div><div className="login-copy"><span className="eyebrow">ONE WORKSPACE. EVERY AGENT.</span><h1>让每一份智能，<br/>成为团队的能力。</h1><p>连接 AI Agent、业务技能与企业工具。<br/>在统一、安全的工作空间，让协作真正发生。</p><div className="login-features"><div><ShieldCheck size={21}/><span>四级角色权限</span></div><div><Layers size={21}/><span>统一能力授权</span></div><div><ScrollText size={21}/><span>完整操作审计</span></div></div></div><small>Agent Hub · 为真实业务而构建</small></section><section className="login-form"><div className="login-form-inner"><span className="eyebrow">WELCOME BACK</span><h2>登录你的工作空间</h2><p>{setupComplete ? '管理员创建成功，请使用刚刚设置的邮箱和密码登录。' : '使用管理员为你开通的企业账号。'}</p><Feedback error={authError}/>{authError && <button className="text-button" onClick={() => void check()}>重新检查服务连接</button>}<Form label="登录工作空间" submit={async f => { await post('/auth/login', { email: value(f, 'email'), password: String(f.get('password')) }); setUser(await api<User>('/auth/me')); setAuthError(''); }} onSuccess={() => {}}><Field label="企业邮箱"><input type="email" name="email" required autoComplete="username" placeholder="name@company.com"/></Field><Field label="密码"><input type="password" name="password" required autoComplete="current-password" placeholder="请输入密码"/></Field></Form><div className="login-foot"><KeyRound size={16}/><span>账号由管理员创建。如需开通，请联系管理员。</span></div></div><small className="login-security"><ShieldCheck size={15}/> 安全会话 · 基于角色的访问控制</small></section></div>;
  return <div className="app-shell">{mobileMenu && <button className="sidebar-backdrop" aria-label="关闭导航" onClick={() => setMobileMenu(false)}/>}<aside className={`sidebar ${mobileMenu ? 'visible' : ''}`}><div className="brand"><span><Bot size={26}/></span><div>Agent Hub<small>企业智能协作平台</small></div></div><div className="workspace-label"><span className="workspace-dot"/>{user.org_id ? `组织 ${user.org_id}` : '全局工作空间'}<ChevronRight size={14}/></div><nav><span className="nav-label">工作空间</span>{navigation.filter(item => canAccessPage(user, item.page)).map(({ page: next, icon: Icon }, i) => <div key={next}>{i === 2 && <span className="nav-label management-label">管理与治理</span>}<button className={page === next ? 'active' : ''} onClick={() => navigate(next)}><Icon size={19}/><span>{pageNames[next]}</span>{page === next && <span className="nav-indicator"/>}</button></div>)}</nav><div className="sidebar-bottom"><div className="workspace-tip"><ShieldCheck size={18}/><span>安全协作，按需授权</span></div><div className="profile"><span className="avatar">{user.name.slice(0, 1)}</span><div><strong>{user.name}</strong><small>{roles[user.role]}</small></div><button aria-label="退出登录" className="icon-button" disabled={logoutBusy} onClick={() => void logout()}>{logoutBusy ? <LoaderCircle className="spin" size={18}/> : <LogOut size={18}/>}</button></div></div></aside><div className="workspace"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-toggle" aria-label="展开导航" onClick={() => setMobileMenu(!mobileMenu)}><Menu size={21}/></button><span>工作空间</span><ChevronRight size={14}/><strong>{pageNames[page]}</strong></div><div className="header-right"><span className="environment">企业工作台</span><span className="avatar small">{user.name.slice(0, 1)}</span></div></header>{logoutError && <Feedback error={logoutError}/>}<main className={page === 'chat' ? 'chat-page' : 'content'}>{!canAccessPage(user, page) ? <Feedback error="当前账号没有访问此页面的权限。"/> : page === 'overview' ? <Overview user={user} navigate={navigate}/> : page === 'chat' ? <Chat key={String(user.id)} user={user} conversationId={route.conversationId} onSelect={(id, replace) => changeRoute({ page: 'chat', conversationId: id }, replace)}/> : <Management key={page} page={page} user={user} navigate={navigate}/>}</main><footer className="workspace-footer"><span>Agent Hub / 智能协作，从这里开始</span><span>按权限显示真实工作空间数据 <ArrowRight size={12}/></span></footer></div><Toaster position="top-right" /></div>;
}
const root = document.getElementById('root');
if (root) createRoot(root).render(<App/>);
