import { DirectoryPanel } from './DirectoryPanel';
import { ScopeFields } from './ScopeFields';
import type { Scope } from './ScopeFields';
import { NewMemberForm } from './NewMemberForm';
import { BatchOnboard } from './BatchOnboard';
import { OnboardingPolicy } from './OnboardingPolicy';
import { AuditPanel } from './AuditPanel';
import { DiscoveredGroups } from './DiscoveredGroups';
import { prepareSkillContent } from './skillContent';
import type { SkillInputMode } from './skillContent';
import { OAuthConfig } from './OAuthConfig';
import { CodexStatus } from './CodexStatus';
import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { Plus, Trash2, RefreshCw, Users, MessagesSquare, Layers, Activity, ArrowUpRight, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { api, post, roles, sameId, dateText, errorText, contact } from './api';
import type { User, Group, Resource, Binding, Identity, Role } from './api';
import { useData, Loading, Empty, Feedback, Modal, Form, Field, Badge, value, nullable } from './ui';
export type Page = 'directory' | 'overview' | 'chat' | 'users' | 'groups' | 'resources' | 'bindings' | 'integrations' | 'audit';
export const pageNames: Record<Page, string> = { directory: '组织与部门', overview: '工作台概览', chat: '智能会话', users: '用户与角色', groups: '协作群组', resources: '能力资源', bindings: '绑定与授权', integrations: 'IM 集成', audit: '审计日志' };
function Table({ headers, rows }: { headers: string[]; rows: ReactNode[][] }) { return rows.length ? <div className="table-wrap"><table><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>)}</tbody></table></div> : <Empty/>; }
export function Overview({ user, navigate }: { user: User; navigate: (page: Page) => void }) {
  const { data, error, loading, reload } = useData<Record<string, number>>('/overview');
  return <><div className="welcome"><div><span className="eyebrow">YOUR AI WORKSPACE</span><h2>{user.name}，欢迎回来</h2><p>让智能能力融入团队的每一次协作。</p><button className="primary" onClick={() => navigate('chat')}>开始智能会话 <ArrowUpRight size={17}/></button></div><div className="welcome-note"><ShieldCheck size={32}/><strong>权限有边界，协作有记录</strong><span>按角色与资源授权访问，操作全程可追溯。</span></div></div><Feedback error={error}/><div className="section-heading"><h2>工作空间概况</h2><button className="text-button" onClick={reload}><RefreshCw size={15}/>刷新</button></div>{loading ? <Loading/> : data && <div className="stats">{([['users', '可见用户', Users], ['groups', '协作群组', Layers], ['conversations', '可见会话', MessagesSquare], ['runs', '执行任务', Activity]] as const).map(([key, label, Icon]) => <div className="stat" key={key}><div className="stat-label">{label}<Icon size={20}/></div><strong>{data[key] ?? '—'}</strong><span>当前账号可访问范围</span></div>)}</div>}{user.role === 'super_admin' && <CodexStatus/>}<div className="section-heading"><h2>从这里开始</h2><span>连接人员、能力与业务</span></div><div className="quick-grid">{([['chat', '与 Agent 一起工作', '查看真实会话与运行结果，使用当前授权的技能和 MCP。'], ['resources', '管理团队智能能力', '统一维护 Skill 内容及远程 MCP 服务。'], ['integrations', '连接企业协作平台', '管理飞书、钉钉身份映射，检查集成状态。']] as const).map(([page, title, desc]) => <button className="quick-card" key={page} onClick={() => navigate(page)}><ArrowUpRight size={20}/><h3>{title}</h3><p>{desc}</p><span>进入{pageNames[page]}</span></button>)}</div></>;
}
export function Management(props: { page: Exclude<Page, 'overview' | 'chat'>; user: User; navigate: (page: Page) => void }) {
  return props.page === 'directory' ? <DirectoryPanel/> : props.page === 'audit' ? <AuditPanel key={props.user.id} userId={String(props.user.id)}/> : <ManagementList {...props}/>;
}
function ManagementList({ page, user, navigate }: { page: Exclude<Page, 'overview' | 'chat'>; user: User; navigate: (page: Page) => void }) {
  const endpoint = page === 'integrations' ? '/identities' : `/${page}`;
  const list = useData<unknown[]>(endpoint);
  const users = useData<User[]>('/users'); const groups = useData<Group[]>('/groups'); const resources = useData<Resource[]>('/resources');
  const [open, setOpen] = useState(false); const [deleting, setDeleting] = useState<string | null>(null);
  const [skillMode, setSkillMode] = useState<SkillInputMode>('body');
  const [kind, setKind] = useState('skill'); const [subject, setSubject] = useState('user'); const [provider, setProvider] = useState('web'); const [role, setRole] = useState<Role>(user.role === 'super_admin' ? 'org_admin' : user.role === 'org_admin' ? 'team_lead' : 'member');
  const canManage = user.role !== 'member' && (!['resources', 'bindings'].includes(page) || ['super_admin', 'org_admin'].includes(user.role));
  const userName = (id: unknown) => users.data?.find(u => String(u.id) === String(id))?.name ?? String(id ?? '—');
  const groupName = (id: unknown) => groups.data?.find(g => String(g.id) === String(id))?.name ?? String(id ?? '—');
  const [scope, setScope] = useState({org: String(user.org_id ?? ''), team: String(user.team_id ?? '')});
  const orgFields = <ScopeFields scope={scope} change={setScope} optionalOrg={page === 'resources'} requireTeam={page === 'users' && ['team_lead','member'].includes(role)} fixedOrg={user.role !== 'super_admin'} fixedTeam={user.role === 'team_lead'}/>;
  async function submit(f: FormData) {
    let body: unknown;
    if (page === 'users') body = { name: value(f, 'name'), email: value(f, 'email'), password: String(f.get('password')), role, org_id: nullable(f, 'org_id'), team_id: nullable(f, 'team_id'), active: true };
    if (page === 'groups') { const ids = f.getAll('members').map(String); if (!ids.length) throw new Error('请至少选择一位群组成员。'); body = { name: value(f, 'name'), org_id: nullable(f, 'org_id'), team_id: nullable(f, 'team_id'), member_ids: ids.map(id => users.data?.find(u => String(u.id) === id)?.id ?? id), provider, external_id: nullable(f, 'external_id') }; }
    if (page === 'resources') { let config: Record<string, unknown>; if (kind === 'skill') { config = { content: await prepareSkillContent(value(f, 'name'), String(f.get('description') ?? ''), String(f.get('content') ?? ''), skillMode) }; } else { const url = new URL(value(f, 'url')); if (url.protocol !== 'https:') throw new Error('MCP 地址必须使用 HTTPS。'); let headers: unknown = {}; try { headers = JSON.parse(value(f, 'headers') || '{}'); } catch { throw new Error('Headers 必须是有效的 JSON 对象。'); } if (!headers || Array.isArray(headers) || typeof headers !== 'object' || Object.values(headers).some(v => typeof v !== 'string')) throw new Error('Headers 必须是字符串键值对。'); config = { url: url.href, headers }; } body = { name: value(f, 'name'), description: value(f, 'description'), kind, org_id: nullable(f, 'org_id'), enabled: f.has('enabled'), config }; }
    if (page === 'bindings') body = { subject_type: subject, subject_id: value(f, 'subject_id'), resource_id: value(f, 'resource_id') };
    if (page === 'integrations') body = { provider: value(f, 'provider'), external_user_id: value(f, 'external_user_id'), user_id: value(f, 'user_id') };
    return post(endpoint, body);
  }
  async function remove(binding: Binding) { if (!window.confirm(`确认删除该授权（${binding.id}）？此操作会撤销对应资源的使用权限。`)) return; setDeleting(String(binding.id)); try { await api(`/bindings/${encodeURIComponent(binding.id)}`, { method: 'DELETE' }); list.reload(); toast.success('授权已撤销。'); } catch (e) { toast.error(errorText(e)); } finally { setDeleting(null); } }
  const [renaming, setRenaming] = useState<User | null>(null);
  async function toggleUser(target: User) {
    const question = target.active
      ? `确认停用「${target.name}」？\n\n立即取消其排队或执行中的任务，清除其网页登录会话以及飞书/钉钉本人授权；之后该用户的消息不再被处理。历史记录、群成员关系和 IM 身份会保留，可随时重新启用（需重新授权本人平台）。`
      : `确认重新启用「${target.name}」？启用后恢复其访问；之前的本人平台授权已被清除，需要重新授权。`;
    if (!window.confirm(question)) return;
    setDeleting(String(target.id));
    try { await api(`/users/${encodeURIComponent(target.id)}`, { method: 'PATCH', body: JSON.stringify({ active: !target.active }) }); list.reload(); users.reload(); toast.success(target.active ? '已停用，其访问已全部切断。' : '已重新启用。'); }
    catch (e) { toast.error(errorText(e)); } finally { setDeleting(null); }
  }
  const [editingGroup, setEditingGroup] = useState<Group | null>(null); const [editBusy, setEditBusy] = useState(false);
  async function removeGroup(group: Group) { if (!window.confirm(`确认从工作台移除“${group.name}"？会保留会话、消息和审计记录；不会删除飞书或钉钉群，也不会清空平台聊天。重新接入需重新审批和授权。`)) return; setDeleting(String(group.id)); try { await api(`/groups/${encodeURIComponent(group.id)}`, {method:'DELETE'}); list.reload(); groups.reload(); toast.success('群组已从工作台移除，历史记录保留。'); } catch(e) { toast.error(errorText(e)); } finally { setDeleting(null); } }
  let content: ReactNode;
  const data = list.data ?? [];
  if (page === 'users') content = <Table headers={['用户', '角色', '组织 / 团队', '状态', '操作']} rows={(data as User[]).map(u => [<div className="person"><span className="avatar">{u.name.slice(0, 1)}</span><div><strong>{u.name}</strong><small>{contact(u)}</small></div></div>, <Badge>{roles[u.role]}</Badge>, `${u.org_id ?? '全局'} / ${u.team_id ?? '—'}`, <Badge tone={u.active ? 'green' : ''}>{u.active ? '正常' : '已停用'}</Badge>, u.can_manage ? <div className="actions"><button className="secondary" disabled={deleting !== null} onClick={() => setRenaming(u)}>改名</button><button className={u.active ? 'danger-button' : 'secondary'} disabled={deleting !== null} onClick={() => void toggleUser(u)}>{deleting === String(u.id) ? '处理中…' : u.active ? '停用' : '启用'}</button></div> : '—'])}/>;
  else if (page === 'groups') content = <><Table headers={['群组', '组织 / 部门', '成员', '来源', '外部群 ID', '操作']} rows={(data as Group[]).map(g => [<strong>{g.name}</strong>, `${g.org_name ?? g.org_id ?? '—'} / ${g.team_name ?? g.team_id ?? '组织级'}`, <span>{g.member_ids.map(userName).join('、') || '暂无成员'}</span>, g.provider === 'web' ? '网页' : g.provider === 'feishu' ? '飞书' : '钉钉', g.external_id ?? '—', <div className="actions">{g.can_edit && <button className="secondary" disabled={deleting !== null} onClick={()=>setEditingGroup(g)}>编辑</button>}{g.can_delete && <button className="danger-button" disabled={deleting !== null} onClick={()=>void removeGroup(g)}>{deleting===String(g.id)?'删除中…':'删除'}</button>}{!g.can_edit && !g.can_delete && '只读'}</div>])}/>{editingGroup && <Modal title="编辑协作群组" close={()=>{if(!editBusy)setEditingGroup(null);}}><Form label="保存" submit={async f=>{setEditBusy(true);try{return await api(`/groups/${encodeURIComponent(editingGroup.id)}`,{method:'PATCH',body:JSON.stringify({name:value(f,'name'),member_ids:f.getAll('members').map(String)})});}finally{setEditBusy(false);}}} onSuccess={()=>{setEditingGroup(null);list.reload();groups.reload();toast.success('群组已保存，成员权限立即更新。');}}><Field label="群组名称"><input name="name" required maxLength={200} defaultValue={editingGroup.name}/></Field><p>组织：{editingGroup.org_name ?? editingGroup.org_id}；部门：{editingGroup.team_name ?? editingGroup.team_id ?? '组织级'}<br/>绑定来源：{editingGroup.provider}；外部群 ID：{editingGroup.external_id ?? '无'}（只读）</p><p>移除成员会立即撤销其群会话访问权限；群组有任务或待发送回复时暂不能修改。</p><div className="check-list">{users.data?.filter(u=>u.active && (u.role==='super_admin' || (sameId(u.org_id,editingGroup.org_id) && (!editingGroup.team_id || sameId(u.team_id,editingGroup.team_id))))).map(u=><label key={u.id}><input type="checkbox" name="members" value={u.id} defaultChecked={editingGroup.member_ids.some(id=>sameId(id,u.id))}/>{u.name}</label>)}</div><Feedback error={users.error}/><button className="secondary" type="button" onClick={()=>setEditingGroup(null)}>取消</button></Form></Modal>}</>;
  else if (page === 'resources') content = data.length ? <div className="resource-grid">{(data as Resource[]).map(r => <article className="resource-card" key={r.id}><div className="resource-head"><span className="resource-icon"><Layers size={22}/></span><Badge tone={r.enabled ? 'green' : ''}>{r.enabled ? '已启用' : '已禁用'}</Badge></div><h3>{r.name}</h3><p>{r.description || '暂无描述'}</p><div className="resource-footer"><Badge>{r.kind.toUpperCase()}</Badge><span>{r.org_id ? `组织 ${r.org_id}` : '全局资源'}</span></div><details><summary>查看配置</summary><pre>{JSON.stringify(r.config, null, 2)}</pre></details></article>)}</div> : <Empty text="还没有能力资源" description="添加 Skill 或远程 MCP，随后为用户与群组授权。"/>;
  else if (page === 'bindings') content = <Table headers={['授权对象', '对象名称', '能力资源', '操作']} rows={(data as Binding[]).map(b => [<Badge>{b.subject_type === 'user' ? '用户' : '群组'}</Badge>, b.subject_type === 'user' ? userName(b.subject_id) : groupName(b.subject_id), resources.data?.find(r => sameId(r.id, b.resource_id))?.name ?? String(b.resource_id), canManage ? <button className="danger-button" disabled={deleting !== null} onClick={() => void remove(b)}><Trash2 size={15}/>{deleting === String(b.id) ? '撤销中…' : '撤销授权'}</button> : '只读'])}/>;
  else if (page === 'integrations') content = <>{user.role === 'super_admin' ? <><IntegrationStatus/><DiscoveryPanel users={users.data ?? []} groups={groups.data ?? []} reloadMappings={() => { list.reload(); groups.reload(); users.reload(); }}/><OnboardingPolicy/><div className="integration-config-grid"><IntegrationConfig provider="feishu"/><IntegrationConfig provider="dingtalk"/></div><div className="integration-config-grid"><OAuthConfig provider="feishu"/><OAuthConfig provider="dingtalk"/></div></> : <div className="notice">平台应用凭据与连接状态仅超级管理员可查看和配置。请联系超级管理员完成接入。</div>}<section className="panel"><div className="section-heading"><h2>员工与群组接入</h2></div><p>应用凭据用于连接平台；员工 Identity 与外部群 ID 用于确认消息身份和授权范围。</p><div className="actions">{canManage && <button className="secondary" onClick={() => setOpen(true)}>绑定员工 Identity</button>}<button className="secondary" onClick={() => navigate('groups')}>配置群外部 ID <ArrowUpRight size={15}/></button></div><p>飞书员工填 open_id，群填 chat_id；钉钉员工填 senderStaffId / userid，群填 conversationId。</p></section><div className="section-heading"><h2>IM 身份绑定</h2><span>外部身份必须显式关联内部用户</span></div><Table headers={['平台', '外部用户 ID', '内部用户']} rows={(data as Identity[]).map(i => [i.provider === 'feishu' ? '飞书' : '钉钉', i.external_user_id, userName(i.user_id)])}/></>;
  else { const records = data as Record<string, unknown>[]; const columns = [...new Set(records.flatMap(Object.keys))]; const names: Record<string, string> = { id: '记录 ID', action: '操作', actor_id: '操作人 ID', user_id: '用户 ID', target_id: '目标 ID', target_type: '目标类型', created_at: '时间', detail: '详情', details: '详情', resource: '资源', ip: '来源 IP' }; content = <Table headers={columns.map(c => names[c] ?? c)} rows={records.map(row => columns.map(c => c === 'created_at' ? dateText(row[c]) : typeof row[c] === 'object' && row[c] !== null ? <pre>{JSON.stringify(row[c], null, 2)}</pre> : String(row[c] ?? '—')))}/>; }
  return <><div className="page-intro"><div><h2>{pageNames[page]}</h2><p>{page === 'bindings' ? '私聊使用用户授权，群聊使用用户与群组授权的交集。' : page === 'audit' ? '查看当前权限范围内的操作记录与监管访问。' : page === 'users' ? '员工无需网页账号：让员工私聊机器人，再到「IM 集成 → 待接入发现」一键接入。这里只用于创建需要登录网页的管理账号。' : '统一管理工作空间，让团队安全、有序地协作。'}</p></div><div className="actions"><button className="secondary" onClick={list.reload} disabled={list.loading}><RefreshCw size={16}/>刷新</button>{page !== 'audit' && canManage && <button className="primary" onClick={() => { setSkillMode('body'); setOpen(true); }}><Plus size={17}/>{page === 'integrations' ? '绑定身份' : page === 'bindings' ? '新增授权' : '新增'}</button>}</div></div>{!canManage && <div className="notice">当前角色没有此页面的管理权限，操作需由有权管理员执行。</div>}<Feedback error={list.error}/>{list.loading ? <Loading/> : content}{page === 'groups' && user.role === 'super_admin' && <DiscoveredGroups groups={(list.data ?? []) as Group[]} reloadGroups={() => { list.reload(); groups.reload(); }}/>} {renaming && <Modal title="修改成员姓名" close={() => setRenaming(null)}><Form label="保存" submit={f => api(`/users/${encodeURIComponent(renaming.id)}`, { method: 'PATCH', body: JSON.stringify({ name: value(f, 'name') }) })} onSuccess={() => { setRenaming(null); list.reload(); users.reload(); toast.success('姓名已更新。'); }}><Field label="姓名"><input aria-label="姓名" name="name" required maxLength={200} defaultValue={renaming.name}/></Field></Form></Modal>} {open && <Modal title={page === 'integrations' ? '绑定 IM 身份' : `新增${pageNames[page]}`} close={() => setOpen(false)}><Form submit={submit} onSuccess={() => { setOpen(false); list.reload(); users.reload(); groups.reload(); resources.reload(); toast.success('已成功保存。'); }}>
    {(page === 'users' || page === 'groups' || page === 'resources') && <Field label="名称"><input name="name" required maxLength={120} placeholder="输入清晰、易识别的名称"/></Field>}
    {page === 'users' && <><Field label="邮箱"><input type="email" name="email" required autoComplete="off"/></Field><Field label="初始密码"><input type="password" name="password" required minLength={12} autoComplete="new-password"/></Field><Field label="角色"><select value={role} onChange={e => setRole(e.target.value as Role)}>{(Object.keys(roles) as Role[]).filter(r => user.role === 'super_admin' ? r !== 'super_admin' : (user.role === 'org_admin' && ['team_lead', 'member'].includes(r)) || (user.role === 'team_lead' && r === 'member')).map(r => <option key={r} value={r}>{roles[r]}</option>)}</select></Field></>}
    {(page === 'users' || page === 'groups' || page === 'resources') && orgFields}
    {page === 'groups' && <><Field label="群组来源"><select value={provider} onChange={e => setProvider(e.target.value)}><option value="web">网页工作台</option><option value="feishu">飞书</option><option value="dingtalk">钉钉</option></select></Field>{provider !== 'web' && <Field label="外部群 ID"><input name="external_id" required/></Field>}<div className="field"><span>选择成员（可多选）</span>{users.loading ? <Loading/> : users.error ? <Feedback error={users.error}/> : !users.data?.length ? <Empty text="暂无可选用户"/> : <div className="check-list" key={`${scope.org}/${scope.team}`}>{users.data.filter(u => u.active && scope.org && (u.role === 'super_admin' || (String(u.org_id) === scope.org && (!scope.team || String(u.team_id) === scope.team)))).map(u => <label key={u.id}><input type="checkbox" name="members" value={u.id}/><span>{u.name}<small>{contact(u)} · {roles[u.role]}</small></span></label>)}</div>}</div></>}
    {page === 'resources' && <><Field label="资源类型"><select value={kind} onChange={e => setKind(e.target.value)}><option value="skill">Skill 技能</option><option value="mcp">MCP 服务</option></select></Field><Field label={kind === 'skill' ? '描述（必填）' : '描述'} hint={kind === 'skill' ? '说明用途和适用任务；正文模式将此描述写入技能触发信息。' : undefined}><textarea name="description" required={kind === 'skill'} maxLength={5000} rows={2} placeholder="说明这项能力适用于什么任务"/></Field>{kind === 'skill' ? <><Field label="Skill 输入模式"><select value={skillMode} onChange={e => setSkillMode(e.target.value as SkillInputMode)}><option value="body">正文（自动生成 YAML 头部）</option><option value="document">完整 SKILL.md（保留原文）</option></select></Field><Field label="Skill 内容" hint={skillMode === 'body' ? '只需填写正文。系统根据资源名称和描述生成头部；中文显示名会生成稳定的技术标识。完整内容含头部最多 64000 字符。' : '粘贴含 --- YAML 头部的完整文件；不会重复生成或修复头部。name 须为小写字母/数字与单连字符，最多 64 字符；description 须为非空字符串（纯数字请加引号）。文件内描述决定触发语义，上方描述用于资源展示。'}><textarea name="content" required rows={9} className="code" placeholder={skillMode === 'body' ? '输入技能说明、使用条件和执行步骤' : '---\nname: “my-skill"\ndescription: “说明用途和适用任务"\n---\n技能正文'}/></Field></> : <><Field label="HTTPS MCP 地址"><input type="url" name="url" required placeholder="https://mcp.example.com/mcp"/></Field><Field label="请求 Headers（JSON）" hint="服务端校验目标地址；读取时凭据会被掩码。"><textarea name="headers" rows={3} className="code" defaultValue="{}"/></Field></>}<label className="checkbox"><input type="checkbox" name="enabled" defaultChecked/>启用此资源</label></>}
    {page === 'bindings' && <><Field label="授权对象类型"><select value={subject} onChange={e => setSubject(e.target.value)}><option value="user">用户</option><option value="group">群组</option></select></Field><Field label="授权对象"><select name="subject_id" required defaultValue="" key={subject}><option value="" disabled>请选择{subject === 'user' ? '用户' : '群组'}</option>{(subject === 'user' ? users.data ?? [] : groups.data ?? []).map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="能力资源"><select name="resource_id" required defaultValue=""><option value="" disabled>请选择资源</option>{resources.data?.filter(r => r.enabled).map(r => <option key={r.id} value={r.id}>{r.name} · {r.kind.toUpperCase()}</option>)}</select></Field><Feedback error={users.error || groups.error || resources.error}/>{(users.loading || groups.loading || resources.loading) && <Loading/>}</>}
    {page === 'integrations' && <><Field label="平台"><select name="provider"><option value="feishu">飞书</option><option value="dingtalk">钉钉</option></select></Field><Field label="外部用户 ID"><input name="external_user_id" required/></Field><Field label="内部用户"><select name="user_id" required defaultValue=""><option value="" disabled>请选择用户</option>{users.data?.filter(u => u.active).map(u => <option key={u.id} value={u.id}>{u.name} · {contact(u)}</option>)}</select></Field>{users.loading && <Loading/>}<Feedback error={users.error}/></>}
  </Form></Modal>}</>;
}
interface Discovery { id: string; provider: string; sender_id: string; chat_id: string; chat_type: string; nickname: string | null; nickname_status?: string; chat_name?: string | null; chat_name_status?: string; first_seen: string; last_seen: string; reason: string; current_reason: string | null; status: string; user_id: string | null }
interface NicknameRefresh { status: string; resolved: number; unresolved: number; remaining: number; cached: number; chat_resolved?: number; chat_unresolved?: number; chat_remaining?: number }
const nicknameReasons: Record<string, string> = { not_resolved: '点击「刷新发现」获取', outside_contact_scope: '不在飞书通讯录权限范围', permission_missing: '应用未开通通讯录或群成员读取权限', bot_not_in_chat: '机器人不在该群', external_chat: '外部群不支持读取成员', name_unavailable: '平台未返回姓名', invalid_id: '外部 ID 格式无法查询', lookup_failed: '查询失败，稍后自动重试', not_provided: '平台事件未提供昵称' };
const chatNameReasons: Record<string, string> = { ...nicknameReasons, permission_missing: '应用未开通群信息读取权限', external_chat: '外部群不支持读取群信息', name_unavailable: '群未设置名称', not_provided: '平台事件未提供群名' };
export function nicknameSummary(r: NicknameRefresh): string | null {
  if (r.status === 'unconfigured') return '飞书应用凭据未配置完整，暂不能补全昵称和群名。';
  if (r.status === 'token_failed') return '飞书应用凭据换取访问令牌失败，本次未补全昵称和群名。';
  if (r.status === 'busy') return '另一次补全正在进行，请稍后再刷新。';
  if (r.status === 'application_changed') return '补全期间飞书应用配置已变更，本次结果已丢弃，请重新刷新。';
  const parts = [r.resolved ? `已补全 ${r.resolved} 个飞书昵称` : '', r.unresolved ? `${r.unresolved} 个昵称未能获取（原因见昵称列）` : '',
    r.chat_resolved ? `已补全 ${r.chat_resolved} 个飞书群名` : '', r.chat_unresolved ? `${r.chat_unresolved} 个群名未能获取（原因见群列）` : '',
    (r.remaining || r.chat_remaining) ? `还有 ${(r.remaining || 0) + (r.chat_remaining || 0)} 项待下次刷新` : ''].filter(Boolean);
  return parts.length ? parts.join('；') + '。' : null;
}
const chatCell = (d: Discovery) => d.chat_type !== 'group' ? d.chat_id : <span>{d.chat_name ? <strong>{d.chat_name}</strong> : <>未知群名 <small>（{chatNameReasons[d.chat_name_status ?? ''] ?? chatNameReasons.not_resolved}）</small></>}<br/><small>{d.chat_id}</small></span>;
const discoveryReasons: Record<string, string> = { unsupported_reply_target: '固定群回调不支持此会话，请切换 Stream', unknown_sender: '发送者尚未绑定', unknown_group: '群尚未登记', not_member: '尚非群成员', inactive_user: '内部用户已停用', outside_group_scope: '组织或团队不符', identity_scope_mismatch: '身份应用归属待确认或不匹配', group_scope_mismatch: '群应用归属待确认或不匹配' };
export function DiscoveryPanel({ users, groups, reloadMappings }: { users: User[]; groups: Group[]; reloadMappings: () => void }) {
  const list = useData<Discovery[]>('/im/discoveries');
  const [selected, setSelected] = useState<Discovery | null>(null);
  const [userId, setUserId] = useState(''); const [groupId, setGroupId] = useState('');
  const [mode, setMode] = useState<'new' | 'existing'>('new'); const [lastScope, setLastScope] = useState<Scope>({ org: '', team: '' });
  const [picked, setPicked] = useState<string[]>([]); const [batchOpen, setBatchOpen] = useState(false);
  const found = list.data ?? [];
  const pickable = (d: Discovery) => d.status === 'pending' && !d.user_id;
  const pickedRows = found.filter(d => picked.includes(d.id));
  // One platform per batch, and one row per sender: a second row of the same sender could only fail.
  const blocked = (d: Discovery) => !pickable(d) || pickedRows.some(p => p.id !== d.id && (p.provider !== d.provider || p.sender_id === d.sender_id));
  useEffect(() => { setPicked(current => current.filter(id => found.some(d => d.id === id && pickable(d)))); }, [list.data]);
  const chosen = users.find(u => String(u.id) === userId);
  const target = groups.find(g => String(g.id) === groupId);
  const [refreshing, setRefreshing] = useState(false);
  const [nicknameNote, setNicknameNote] = useState<string | null>(null);
  const refresh = async () => {
    setRefreshing(true);
    try { setNicknameNote(nicknameSummary(await post<NicknameRefresh>('/im/discoveries/nicknames', {}))); }
    catch (error) { setNicknameNote('飞书昵称补全失败：' + errorText(error)); }
    finally { setRefreshing(false); list.reload(); }
  };
  return <section className="panel"><div className="section-heading"><h2>待接入发现</h2><div className="actions"><button className="secondary" disabled={!picked.length} onClick={() => setBatchOpen(true)}>批量接入{picked.length ? `（${picked.length}）` : ''}</button><button className="secondary" onClick={refresh} disabled={list.loading || refreshing}><RefreshCw size={15}/>{refreshing ? '获取昵称与群名中…' : '刷新发现'}</button></div></div><p>先让员工私聊机器人，或将机器人加入群后发送一条文本消息，再刷新此表。员工无需网页账号，点「处理接入」即可为其建立仅 IM 成员。发现不等于授权；仅超级管理员处理全局发现。展示最近 500 条。</p><p>授权前的消息不会执行或回放。完成身份、群映射及成员确认后，必须重新发送消息。Skill / MCP 仍取用户与群授权的交集。</p><p>钉钉昵称与群名取自消息事件；飞书事件不含二者，刷新时由服务端用应用凭据查询通讯录（群聊可回退群成员列表）和群信息，每次各最多补全 20 项。</p>{nicknameNote && <p className="notice">{nicknameNote}</p>}<Feedback error={list.error}/>{list.loading ? <Loading/> : <Table headers={['选择', '平台 / 昵称', '发送者外部 ID', '群 / 会话 ID', '类型', '首次 / 最近发现', '原因 / 状态', '操作']} rows={found.map(d => [<input type="checkbox" aria-label={`选择 ${d.nickname || d.sender_id}`} checked={picked.includes(d.id)} disabled={!picked.includes(d.id) && blocked(d)} onChange={e => setPicked(e.target.checked ? [...picked, d.id] : picked.filter(id => id !== d.id))}/>, <span>{d.provider === 'feishu' ? '飞书' : '钉钉'} / {d.nickname || <>无昵称<br/><small>{nicknameReasons[d.nickname_status ?? ''] ?? nicknameReasons.not_resolved}</small></>}</span>, d.sender_id, chatCell(d), d.chat_type === 'group' ? '群聊' : '私聊', <span>{dateText(d.first_seen)}<br/>{dateText(d.last_seen)}</span>, <span>{discoveryReasons[d.current_reason ?? d.reason] ?? d.reason}<br/>{d.status === 'authorized' ? '已授权，请重发' : d.status === 'stale_application' ? '旧应用（不可绑定）' : '待审批'}</span>, <button className="secondary" disabled={d.status === 'stale_application'} onClick={() => { setSelected(d); setMode(d.user_id ? 'existing' : 'new'); setUserId(d.user_id ?? ''); setGroupId(''); }}>处理接入</button>])}/>} {selected && <Modal title="确认 IM 接入与成员" close={() => setSelected(null)}><p>平台：{selected.provider}<br/>发送者：{selected.sender_id}<br/>会话：{selected.chat_id}</p><Field label="接入方式"><select value={mode} onChange={e => setMode(e.target.value as 'new' | 'existing')}><option value="new" disabled={!!selected.user_id}>新建 IM 成员（无需网页账号）</option><option value="existing">绑定已有用户</option></select></Field>{mode === 'new' ? <NewMemberForm key={selected.id} discoveryId={selected.id} nickname={selected.nickname} isGroup={selected.chat_type === 'group'} initialScope={lastScope} done={scope => { setLastScope(scope); setSelected(null); list.reload(); reloadMappings(); toast.success('已创建 IM 成员并绑定身份。请让对方重新发送消息；Skill / MCP 仍需单独授权。'); }}/> : <Form label="确认保存" submit={async f => {
    const newGroup = groupId === 'new' ? { name: value(f, 'name'), org_id: chosen?.org_id, team_id: chosen?.team_id, provider: selected.provider, external_id: selected.chat_id, member_ids: f.getAll('members').map(String) } : null;
    return post(`/im/discoveries/${selected.id}/approve`, { user_id: userId, group_id: groupId && groupId !== 'new' ? groupId : null, new_group: newGroup, confirm_member: f.has('confirm_member') });
  }} onSuccess={() => { setSelected(null); list.reload(); reloadMappings(); toast.success('已保存。请重新发送消息；未完成群登记和成员确认时，群消息仍不会执行。'); }}><Field label="绑定内部已有用户"><select required value={userId} onChange={e => { setUserId(e.target.value); setGroupId(''); }}><option value="">请选择用户</option>{users.filter(u => u.active).map(u => <option key={u.id} value={String(u.id)}>{u.name} · {contact(u)} · {u.org_id ?? '全局'}</option>)}</select></Field>{selected.chat_type === 'group' && <><Field label="群登记"><select value={groupId} onChange={e => setGroupId(e.target.value)}><option value="">仅绑定身份，稍后继续群登记</option><option value="new" disabled={!chosen?.org_id}>创建新群（已预填平台与外部 ID）</option>{groups.filter(g => g.provider === selected.provider && (!g.external_id || g.external_id === selected.chat_id) && (chosen?.role === 'super_admin' || (sameId(g.org_id, chosen?.org_id) && (!g.team_id || sameId(g.team_id, chosen?.team_id))))).map(g => <option key={g.id} value={String(g.id)}>{g.name}</option>)}</select></Field>{groupId === 'new' && <><Field label="群名称"><input name="name" required maxLength={200} defaultValue={`${selected.provider === 'feishu' ? '飞书' : '钉钉'}协作群`}/></Field><p>组织 / 团队：{chosen?.org_id} / {chosen?.team_id ?? '—'}；外部 ID 已预填：{selected.chat_id}</p><div className="check-list">{users.filter(u => u.active && sameId(u.org_id, chosen?.org_id) && (!chosen?.team_id || sameId(u.team_id, chosen.team_id))).map(u => <label key={u.id}><input type="checkbox" name="members" value={String(u.id)}/>{u.name}</label>)}</div><p>请明确勾选成员，必须包含本次发送者所绑定的用户。</p></>}{groupId && <><p>{target ? `现有成员：${target.member_ids.map(id => users.find(u => sameId(u.id, id))?.name ?? id).join('、')}。本次会明确加入所选发送者。` : '仅添加上方明确勾选的成员。'}</p><label className="checkbox"><input type="checkbox" name="confirm_member" required/>我确认群映射与上述成员关系，不授予任何 Skill / MCP</label></>}</>}<p>换应用后的旧映射不可覆盖，请核查冲突；保存后必须重发消息。</p></Form>}</Modal>}{batchOpen && <Modal title="批量接入 IM 成员" close={() => setBatchOpen(false)}><BatchOnboard rows={pickedRows} initialScope={lastScope} progress={(_created, scope) => { setLastScope(scope); list.reload(); reloadMappings(); }} done={scope => { setLastScope(scope); setBatchOpen(false); setPicked([]); list.reload(); reloadMappings(); toast.success('已批量创建 IM 成员并绑定身份。请让他们重新发送消息；Skill / MCP 仍需单独授权。'); }}/></Modal>}</section>;
}
const connectionLabels: Record<string, string> = { missing_credentials: '未配置完整', webhook_configured: '回调已配置（未验证连接）', connection_unobserved: '等待连接进程', connecting: '连接中 / 重连中', connected: '已连接', stale: '心跳已过期', stopped: '已停止', configuration_changed: '已保存，等待重连', invalid_config: '模式无效' };
function IntegrationStatus() {
  const [revision, setRevision] = useState(0);
  useEffect(() => { const saved = () => setRevision(v => v + 1); window.addEventListener('hub-integration-config-saved', saved); return () => window.removeEventListener('hub-integration-config-saved', saved); }, []);
  return <IntegrationStatusBody key={revision}/>;
}
function IntegrationStatusBody() {
  const state = useData<Record<string, { configured: boolean; transport?: string; state?: string; missing?: string[]; native_work_status?: { state: string; error?: string; message: string; required_permissions?: string[] } }>>('/integrations/status');
  return <section className="panel"><div className="section-heading"><h2>服务连接状态</h2><button className="text-button" onClick={state.reload}><RefreshCw size={14}/>刷新状态</button></div><Feedback error={state.error}/>{state.loading ? <Loading/> : state.data && <div className="status-grid">{Object.entries(state.data).map(([key, val]) => <div key={key}><strong>{key === 'feishu' ? '飞书' : key === 'dingtalk' ? '钉钉' : key}</strong><p>{val.transport} · {val.configured ? '配置齐全' : '未配置完整'}</p><Badge tone={val.state === 'connected' ? 'green' : ''}>{connectionLabels[val.state ?? ''] ?? '执行服务配置'}</Badge>{val.native_work_status && <p className="im-help">{val.native_work_status.message}<br/>原生标记：{val.native_work_status.state}{val.native_work_status.error ? ` · ${val.native_work_status.error}` : ''}{val.native_work_status.required_permissions?.length ? `；权限：${val.native_work_status.required_permissions.join('、')}` : ''}</p>}{!!val.missing?.length && <small className="im-missing">缺少：{val.missing.join('、')}</small>}</div>)}</div>}<p className="im-help">保存后点击刷新状态。长连接监督进程每 5 秒检查更新；只有实际 socket 打开才显示已连接，连接成功不代表平台权限或消息收发已验收。</p></section>;
}
interface IMConfig { provider: string; revision: number; source: string; transport: string; fields: Record<string, string>; secrets_set: Record<string, boolean> }
const fieldLabels: Record<string, string> = { APP_ID: 'App ID', APP_SECRET: 'App Secret', CLIENT_ID: 'Client ID', CLIENT_SECRET: 'Client Secret', ROBOT_CODE: 'Robot Code', VERIFICATION_TOKEN: 'Verification Token', ENCRYPT_KEY: 'Encrypt Key', ROBOT_ACCESS_TOKEN: '固定群 Robot Access Token', ROBOT_CHAT_ID: '固定群 Conversation ID', ROBOT_SECRET: '固定群签名 Secret（可选）' };
function IntegrationConfig({ provider }: { provider: 'feishu' | 'dingtalk' }) {
  const config = useData<IMConfig>(`/integrations/config/${provider}`);
  return <section className="panel"><div className="section-heading"><h2>{provider === 'feishu' ? '飞书应用配置' : '钉钉应用配置'}</h2><button className="text-button" onClick={config.reload}>重新加载</button></div><Feedback error={config.error}/>{config.loading ? <Loading/> : config.data && <ConfigForm key={`${provider}-${config.data.revision}`} config={config.data} reload={config.reload}/>}</section>;
}
import { useForm } from 'react-hook-form';

function ConfigForm({ config, reload }: { config: IMConfig; reload: () => void }) {
  const [mode, setMode] = useState(config.transport); const [cleared, setCleared] = useState<string[]>([]);
  const feishu = config.provider === 'feishu';
  const fields = feishu ? ['APP_ID', 'APP_SECRET', ...(mode === 'webhook' ? ['VERIFICATION_TOKEN', 'ENCRYPT_KEY'] : [])] : mode === 'stream' ? ['CLIENT_ID', 'CLIENT_SECRET', 'ROBOT_CODE'] : ['CLIENT_ID', 'ROBOT_CODE', 'APP_SECRET', 'ROBOT_ACCESS_TOKEN', 'ROBOT_CHAT_ID', 'ROBOT_SECRET'];
  
  const { register, handleSubmit, formState: { isSubmitting } } = useForm();
  
  return <><p>{config.source === 'database' ? `已保存至加密配置 · 版本 ${config.revision}` : '当前使用环境配置 · 尚未网页保存'}</p><form onSubmit={handleSubmit(async (data) => {
    const values = Object.fromEntries(fields.map(name => [name, cleared.includes(name) ? '' : String(data[name] ?? '')]));
    try {
      await api(`/integrations/config/${config.provider}`, { method: 'PUT', body: JSON.stringify({ revision: config.revision, transport: mode, fields: values, clear: cleared }) });
      toast.success('配置已保存'); reload(); window.dispatchEvent(new Event('hub-integration-config-saved'));
    } catch (e) {
      toast.error(errorText(e));
    }
  })}><fieldset disabled={isSubmitting} style={{ border: 'none', padding: 0, margin: 0 }}><Field label="接入模式"><select value={mode} onChange={e => { setMode(e.target.value); setCleared([]); }}><option value={feishu ? 'websocket' : 'stream'}>{feishu ? 'WebSocket 长连接' : 'Stream 长连接'}</option><option value="webhook">{feishu ? 'Webhook 回调' : 'Legacy Webhook 固定群'}</option></select></Field>{fields.map(name => { const secret = name in config.secrets_set; return <div key={name}><Field label={fieldLabels[name]} hint={secret ? config.secrets_set[name] ? '已设置；留空保留原值。不会返回或显示已有密钥。' : '尚未设置' : '留空保留；清空已有值请勾选下方清除。'}><input {...register(name)} type={secret ? 'password' : 'text'} autoComplete="off" defaultValue={secret ? '' : config.fields[name] ?? ''} disabled={cleared.includes(name)} maxLength={4096}/></Field><label className="checkbox im-clear"><input type="checkbox" checked={cleared.includes(name)} onChange={e => setCleared(e.target.checked ? [...cleared, name] : cleared.filter(x => x !== name))}/>保存时明确清除 {fieldLabels[name]}</label></div>; })}<p className="im-help">保存即生效：回调和回复读取新配置，常驻连接按更新重连。清除必填凭据会停止连接；留空不会清除。测试连接未提供，请按实际连接状态和平台后台检查。</p><div className="form-actions"><button className="primary" type="submit" disabled={isSubmitting}>{isSubmitting && <RefreshCw size={16} className="spin"/>}{isSubmitting ? '正在提交…' : '保存应用配置'}</button></div></fieldset></form></>;
}
