import { useState } from 'react';
import { toast } from 'sonner';
import { api } from './api';
import { useData, Loading, Feedback, Modal, Form, Field, value } from './ui';
type Config = { provider: string; revision: number; configured: boolean; message: string; fields: Record<string,string>; secrets_set: Record<string,boolean> };
export function OAuthConfig({ provider }: { provider: 'feishu' | 'dingtalk' }) {
  const config = useData<Config>(`/integrations/oauth/${provider}`);
  const [open, setOpen] = useState(false); const [clear, setClear] = useState<string[]>([]);
  return <section className="panel"><div className="section-heading"><h2>{provider === 'feishu' ? '飞书' : '钉钉'}个人 OAuth / CLI 授权配置</h2><button className="secondary" onClick={() => { setClear([]); setOpen(true); }}>配置个人授权</button></div><Feedback error={config.error}/>{config.loading ? <Loading/> : config.data && <><p>{config.data.configured ? '应用字段已配置；设备授权与本人 Identity 仍须验证' : 'setup_required：缺少独立个人 OAuth 应用配置'}</p><p>{config.data.message}</p></>}{open && config.data && <Modal title="个人 OAuth / CLI 授权配置" close={() => setOpen(false)}><Form label="保存个人授权配置" submit={f => api(`/integrations/oauth/${provider}`, {method:'PUT', body:JSON.stringify({revision:config.data!.revision, fields:Object.fromEntries(['CLIENT_ID','CLIENT_SECRET','SCOPES'].map(name => [name,clear.includes(name) ? '' : value(f,name)])),clear})})} onSuccess={() => {setOpen(false);config.reload();toast.success('个人授权配置已保存');window.dispatchEvent(new Event('hub-integration-config-saved'));}}>{['CLIENT_ID','CLIENT_SECRET','SCOPES'].map(name => <div key={name}><Field label={`PLATFORM_${provider.toUpperCase()}_${name}`} hint={name === 'CLIENT_SECRET' ? config.data!.secrets_set[name] ? '已设置；留空保留，永不回显' : '未设置；不会自动复用机器人密钥' : undefined}><input name={name} type={name === 'CLIENT_SECRET' ? 'password' : 'text'} defaultValue={config.data!.fields[name] ?? ''} readOnly={name === 'SCOPES'} disabled={clear.includes(name)} autoComplete="off" maxLength={4096}/></Field>{name !== 'SCOPES' && <label className="checkbox"><input type="checkbox" checked={clear.includes(name)} onChange={e=>setClear(e.target.checked ? [...clear,name] : clear.filter(x=>x!==name))}/>明确清除 {name}</label>}</div>)}<p>仅允许已批准的最小权限。自建应用不保证支持设备授权，请在官方后台确认开通。员工仍需绑定本人平台 Identity。</p></Form></Modal>}</section>;
}
