import { useState } from 'react';
import { api, errorText } from './api';
import { useData, Loading, Feedback } from './ui';
type Connection = { provider: 'feishu' | 'dingtalk'; state: string; scope: string; message: string; authorization_url?: string; user_code?: string; expires_at?: string };
const labels: Record<string, string> = { disconnected: '未连接', starting: '正在发起', pending: '待授权', connected: '已连接，请重发任务', setup_required: '需要管理员配置', expired: '已过期', platform_rejected: '平台拒绝或暂不可用', identity_mismatch: '授权身份不符', interrupted: '授权中断，请重新发起' };
function safeLink(c: Connection) { try { const u = new URL(c.authorization_url ?? ''); return u.protocol === 'https:' && !u.username && !u.password && (!u.port || u.port === '443') && (c.provider === 'feishu' ? ['accounts.feishu.cn','open.feishu.cn'] : ['login.dingtalk.com','open-dev.dingtalk.com']).includes(u.hostname); } catch { return false; } }
export function PlatformConnections() {
  const list = useData<Connection[]>('/platform-connections', 5000);
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function action(provider: string, op: string) { setBusy(true); setError(''); try { await api(`/platform-connections/${provider}/${op}`, { method: 'POST' }); list.reload(); } catch(e) { setError(errorText(e)); } finally { setBusy(false); } }
  return <><div className="page-intro"><div><h2>个人平台连接</h2><p>仅显示你的个人授权。请本人打开授权页并同意，完成后后台确认状态，请重新发送任务。</p></div><button className="secondary" disabled={busy} onClick={list.reload}>刷新列表</button></div><Feedback error={error || list.error}/><div className="notice">断开只删除 Hub 保存的凭据，不会撤销平台授权；如需彻底撤权，请前往平台授权管理。当前接入身份授权，不代表已支持文档或图片解析。</div>{list.loading ? <Loading/> : <div className="resource-grid">{list.data?.map(c => <section className="resource-card" key={c.provider}><h3>{c.provider === 'feishu' ? '飞书' : '钉钉'}</h3><strong>{labels[c.state] ?? '未知状态'}</strong><p>{c.message}</p><p>权限：{c.scope}</p>{c.expires_at && <p>有效期至：{new Date(c.expires_at).toLocaleString()}</p>}{c.state === 'setup_required' && <a href="#/integrations">管理员 OAuth 配置入口</a>}{c.state === 'pending' && <div role="status"><p>以下授权材料仅供本人使用，请勿转发到群聊。</p>{safeLink(c) && <a href={c.authorization_url} target="_blank" rel="noopener noreferrer">打开官方授权页面</a>}<p>设备码：<code>{c.user_code}</code></p></div>}<div className="actions"><button className="primary" disabled={busy || ['pending','connected','starting','setup_required'].includes(c.state)} onClick={() => void action(c.provider, 'start')}>发起授权</button><button className="secondary" disabled={busy} onClick={() => void action(c.provider, 'refresh')}>刷新状态</button>{c.state === 'pending' && <button className="secondary" disabled={busy} onClick={() => void action(c.provider, 'cancel')}>取消</button>}<button className="danger-button" disabled={busy} onClick={() => void action(c.provider, 'disconnect')}>断开 Hub 连接</button></div></section>)}</div>}</>;
}
